language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t kapatel123/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true kapatel123/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "docker1"
    env: "Docker1-env"
    bucket_name: "elasticbeanstalk-us-east-1-767131022863"
    bucket_path: "docker1"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY